version: '3.8'
services:
  node-app:
    container_name: node_ce
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - my-network
    environment:
      - NODE_ENV=.env
    volumes:
      - ./:/app/

  postgres-db:
    container_name: postgres_ce
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5430:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
